# Generated by Django 5.0.1 on 2025-06-08 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_replied', models.BooleanField(default=False, verbose_name='Replied')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('project_type', models.CharField(choices=[('website', 'Website Development'), ('game', 'Game Development'), ('mobile', 'Mobile App Development'), ('django', 'Django Backend'), ('other', 'Other')], max_length=20, verbose_name='Project Type')),
                ('budget_range', models.CharField(choices=[('5k-15k', '₹5,000 - ₹15,000'), ('15k-30k', '₹15,000 - ₹30,000'), ('30k-50k', '₹30,000 - ₹50,000'), ('50k-1l', '₹50,000 - ₹1,00,000'), ('1l+', '₹1,00,000+')], max_length=20, verbose_name='Budget Range')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('deadline', models.CharField(max_length=50, verbose_name='Deadline')),
                ('features_needed', models.TextField(blank=True, verbose_name='Features Needed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
